### obtener una reserva por su id
GET http://localhost:8081/api/bookings/4

### Buscamos una reserva que no exista
GET http://localhost:8081/api/bookings/90

### crear una nueva reserva -> Code 201
POST http://localhost:8081/api/bookings
Content-Type: application/json;

{   
    "clientName": "Lionel Messi",
    "clientEmail": "leomessi10@gmail.com",
    "date": "06-24-1987",
    "time": "00:00:06",
    "status": "Confirmada",
    "services": []
}

### crear una nueva reserva (Sin importar si viene con un id en el cuerpo) -> Code 201
POST http://localhost:8081/api/bookings
Content-Type: application/json;

{   
    "id": 323424,
    "clientName": "Pedro Pérez",
    "clientEmail": "pedroperez@gmail.com",
    "date": "01-01-2000",
    "time": "00:00:10",
    "status": "Confirmada",
    "services": []
}

### crear una nueva reserva con campos faltantes -> Code 400
POST http://localhost:8081/api/bookings
Content-Type: application/json;

{
    "clientName": "CR7",
    "clientEmail": "siuu7@gmail.com",
    "status": "Eliminado",
    "services": []
}

### Agrego un servicio a una reserva. todo valido (bid=1, sid=1) 
POST http://localhost:8081/api/bookings/1/services/1
### primer intento. Deberia incrementar quantity en 2
### segundo intento. quantity en 3

POST http://localhost:8081/api/bookings/4/services/2
### primer intento. Deberia aparecer el servicio con sid=2 en la reserva con bid=4
### segundo intento. service: 2 quantity: 2. En bid=4

### Con un sid que no existe 
POST http://localhost:8081/api/bookings/1/services/2343

### Con un bid que no existe 
POST http://localhost:8081/api/bookings/1231/services/2343

### Con ambos bid y sid inexistentes
POST http://localhost:8081/api/bookings/2131231/services/2343



